In [16]:
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from pandas import DataFrame as df
import pandas as pd
from datetime import date, timedelta
yesterdays_date = (date.today() - timedelta(days=1)).strftime('%-m/%d/%y')
date_2_days_ago = (date.today() - timedelta(days=2)).strftime('%-m/%d/%y')
date_3_days_ago = (date.today() - timedelta(days=3)).strftime('%-m/%d/%y')
date_4_days_ago = (date.today() - timedelta(days=4)).strftime('%-m/%d/%y')
date_5_days_ago = (date.today() - timedelta(days=5)).strftime('%-m/%d/%y')
date_6_days_ago = (date.today() - timedelta(days=6)).strftime('%-m/%d/%y')
date_7_days_ago = (date.today() - timedelta(days=7)).strftime('%-m/%d/%y')
date_8_days_ago = (date.today() - timedelta(days=8)).strftime('%-m/%d/%y')

confirmed_url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'
deaths_url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv'

confirmed = pd.read_csv(confirmed_url)
deaths = pd.read_csv(deaths_url)
confirmed.iloc[0]['Country/Region'] #Test

def new_cases_columns(frame): #Makes 7 columns of new cases
    new_yest = [confirmed.iloc[i][yesterdays_date] - confirmed.iloc[i][date_2_days_ago] for i in range(len(frame))]
    new_2_ago = [confirmed.iloc[i][date_2_days_ago] - confirmed.iloc[i][date_3_days_ago] for i in range(len(frame))]
    new_3_ago = [confirmed.iloc[i][date_3_days_ago] - confirmed.iloc[i][date_4_days_ago] for i in range(len(frame))]
    new_4_ago = [confirmed.iloc[i][date_4_days_ago] - confirmed.iloc[i][date_5_days_ago] for i in range(len(frame))]
    new_5_ago = [confirmed.iloc[i][date_5_days_ago] - confirmed.iloc[i][date_6_days_ago] for i in range(len(frame))]
    new_6_ago = [confirmed.iloc[i][date_6_days_ago] - confirmed.iloc[i][date_7_days_ago] for i in range(len(frame))]
    new_7_ago = [confirmed.iloc[i][date_7_days_ago] - confirmed.iloc[i][date_8_days_ago] for i in range(len(frame))]
    confirmed['new_yest'] = df(new_yest)
    confirmed['new_2_ago'] = df(new_2_ago)
    confirmed['new_3_ago'] = df(new_3_ago)
    confirmed['new_4_ago'] = df(new_4_ago)
    confirmed['new_5_ago'] = df(new_5_ago)
    confirmed['new_6_ago'] = df(new_6_ago)
    confirmed['new_7_ago'] = df(new_7_ago)

new_cases_columns(confirmed)    

x = confirmed[confirmed["Country/Region"] == "Italy"].iloc[0]['new_yest']
print(x)

def change_past_week(frame):
    return frame.iloc[0]['new_yest']
new_cases_italy = change_past_week(confirmed[confirmed['Country/Region'] == 'Italy'])
print(new_cases_italy)

5974
5974

In [5]:
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
import dash_core_components as dcc
import plotly
from pandas import DataFrame as df
import pandas as pd
from datetime import date, timedelta
import plotly.graph_objects as go

yesterdays_date = (date.today() - timedelta(days=1)).strftime('%-m/%-d/%y')
date_2_days_ago = (date.today() - timedelta(days=2)).strftime('%-m/%-d/%y')
date_3_days_ago = (date.today() - timedelta(days=3)).strftime('%-m/%-d/%y')
# date_4_days_ago = (date.today() - timedelta(days=4)).strftime('%-m/%-d/%y')
# date_5_days_ago = (date.today() - timedelta(days=5)).strftime('%-m/%-d/%y')
# date_6_days_ago = (date.today() - timedelta(days=6)).strftime('%-m/%-d/%y')
# date_7_days_ago = (date.today() - timedelta(days=7)).strftime('%-m/%-d/%y')
# date_8_days_ago = (date.today() - timedelta(days=8)).strftime('%-m/%-d/%y')
# x_axis = [date_7_days_ago, date_6_days_ago, date_5_days_ago, date_4_days_ago,
# date_3_days_ago, date_2_days_ago, yesterdays_date]
cloudcafeblue = 'rgb(46, 162, 190)'
cardchildstyle = {'padding': '1.5em',}
#This x-axis corresponds to the graph of new cases per day.

confirmed_url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'
deaths_url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv'
recovered_url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv'

confirmed = pd.read_csv(confirmed_url)
deaths = pd.read_csv(deaths_url)
recovered = pd.read_csv(recovered_url)

def new_cases_columns(frame): #Makes 7 columns of new cases
    new_yest = [confirmed.iloc[i][yesterdays_date] - confirmed.iloc[i][date_2_days_ago] for i in range(len(frame))]
    new_2_ago = [confirmed.iloc[i][date_2_days_ago] - confirmed.iloc[i][date_3_days_ago] for i in range(len(frame))]
    # new_3_ago = [confirmed.iloc[i][date_3_days_ago] - confirmed.iloc[i][date_4_days_ago] for i in range(len(frame))]
    # new_4_ago = [confirmed.iloc[i][date_4_days_ago] - confirmed.iloc[i][date_5_days_ago] for i in range(len(frame))]
    # new_5_ago = [confirmed.iloc[i][date_5_days_ago] - confirmed.iloc[i][date_6_days_ago] for i in range(len(frame))]
    # new_6_ago = [confirmed.iloc[i][date_6_days_ago] - confirmed.iloc[i][date_7_days_ago] for i in range(len(frame))]
    # new_7_ago = [confirmed.iloc[i][date_7_days_ago] - confirmed.iloc[i][date_8_days_ago] for i in range(len(frame))]
    confirmed['new_yest'] = df(new_yest)
    confirmed['new_2_ago'] = df(new_2_ago)
    # confirmed['new_3_ago'] = df(new_3_ago)
    # confirmed['new_4_ago'] = df(new_4_ago)
    # confirmed['new_5_ago'] = df(new_5_ago)
    # confirmed['new_6_ago'] = df(new_6_ago)
    # confirmed['new_7_ago'] = df(new_7_ago)

new_cases_columns(confirmed)

confirmed['Percent Change'] = [confirmed.iloc[i][new_yest] / confirmed.iloc[i][new_2_ago] - 1 for i in range(len(confirmed))]

confirmed.sort_values(by=['Percent Change'])

/home/bo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:51: RuntimeWarning:

invalid value encountered in long_scalars

/home/bo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:51: RuntimeWarning:

divide by zero encountered in long_scalars

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/24/20,3/25/20,3/26/20,3/27/20,3/28/20,3/29/20,3/30/20,new_yest,new_2_ago,Percent Change
125,NaN,Guyana,5.000000,-58.750000,0,0,0,0,0,0,...,5,5,5,5,8,8,8,0,0,0.0
101,NaN,Eritrea,15.179400,39.782300,0,0,0,0,0,0,...,1,4,6,6,6,12,12,0,6,0.0
100,NaN,Equatorial Guinea,1.500000,10.000000,0,0,0,0,0,0,...,9,9,12,12,12,12,12,0,0,0.0
95,NaN,Djibouti,11.825100,42.590300,0,0,0,0,0,0,...,3,11,11,12,14,18,18,0,4,0.0
93,Greenland,Denmark,71.706900,-42.604300,0,0,0,0,0,0,...,5,6,6,10,10,10,10,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,NaN,Saint Kitts and Nevis,17.357822,-62.782998,0,0,0,0,0,0,...,0,2,2,2,2,2,7,5,0,2.5
242,NaN,Guinea-Bissau,11.803700,-15.180400,0,0,0,0,0,0,...,0,2,2,2,2,2,8,6,0,3.0
253,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,0,0,0,0,0,0,3,3,0,inf
231,Diamond Princess,Canada,0.000000,0.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
238,Recovered,Canada,0.000000,0.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN